### ISSUE TITLE
missin key 'Alt' in Font

### ISSUE THREAD

**Issue by xxzozaxx** [aarzilli/yacco#1]
Hi,

I want to try out yacco on linux machine (Debian GNU/Linux) and compilin run fine. but at run time I have this error message

```
Could not load configuration file: missing key 'Alt' in Fonts
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5f377c]

goroutine 1 [running]:
github.com/aarzilli/yacco/textframe.(*Frame).Init(0xdd7e60, 0x5, 0x9b6845, 0x4)
        /home/master/Programs/0TextEditors/yacco/textframe/frame.go:128 +0x18c
main.(*Window).Init(0xdd7e00, 0xa6f180, 0xc0001b6000, 0x0, 0x0, 0x0, 0xc0000b1d38)
        /home/master/Programs/0TextEditors/yacco/win.go:151 +0x576
main.realmain(0xa6f180, 0xc0001b6000)
        /home/master/Programs/0TextEditors/yacco/yacco.go:105 +0xef
golang.org/x/exp/shiny/driver/x11driver.main(0x9dc248, 0x0, 0x0)
        /home/master/.go/pkg/mod/github.com/aarzilli/exp@v0.0.0-20180724135916-edb5f9d2bb76/shiny/driver/x11driver/x11driver.go:58 +0x259
golang.org/x/exp/shiny/driver/x11driver.Main(0x9dc248)
        /home/master/.go/pkg/mod/github.com/aarzilli/exp@v0.0.0-20180724135916-edb5f9d2bb76/shiny/driver/x11driver/x11driver.go:31 +0x2f
golang.org/x/exp/shiny/driver.main(...)
        /home/master/.go/pkg/mod/github.com/aarzilli/exp@v0.0.0-20180724135916-edb5f9d2bb76/shiny/driver/driver_x11.go:15
golang.org/x/exp/shiny/driver.Main(...)
        /home/master/.go/pkg/mod/github.com/aarzilli/exp@v0.0.0-20180724135916-edb5f9d2bb76/shiny/driver/driver.go:24
main.main()
        /home/master/Programs/0TextEditors/yacco/yacco.go:197 +0x13a
```

NOTE: I have empty `rc` config file

**Comment by aarzilli** [comment]
you really need to run the install script like the README says.

**Comment by xxzozaxx** [comment]
@aarzilli 
and that's exactly what I did. I mkdir called bin and run the script on this dir.

**Comment by xxzozaxx** [comment]
I pull the new commit and still not working.

**Comment by aarzilli** [comment]
I'd guess that you created the .config/yacco/rc file some other way before executing the install script, so you'd have to manually delete it. Also a `bin` directory inside the clone directory won't work (it's used for the build process) and the argument of `install.sh` should be a full path.
